### ISSUE TITLE
MobaxTerm drag & drop from Windows to Linux

### ISSUE THREAD

**Issue by pietrobr** [Microsoft/sqllinuxlabs#6]
Using MobaxTerm from Windows to Linux drag & drop when restoring the database break the script files (cpww.sh, restoreww.sh, etc) that don't work. Using git clone directly from inside the Linux VM solve the problem.

**Comment by rgward** [comment]
Great suggestion to use git clone for all scripts files. We will make changes to the labs to do that

**Comment by rgward** [comment]
This is now fixed. Have added instructions in prelab to clone repo with git
